# This is a basic workflow to help you get started with Actions

name: Compile Markdown to Single PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "poc" branch
  push:
    branches: [ "poc" ]
  pull_request:
    branches: [ "poc" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile-to-pdf:
    name: Compile Markdown to PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra

      - name: Compile Markdown to PDF
        run: |
          mkdir -p pdf
          pandoc your-directory/**/*.md -o pdf/compiled.pdf
          # Adjust the path to your Markdown files and specify the output PDF name

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: pdf/compiled.pdf
